apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  namespace: default
spec:
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
       - image: postgres
         name: postgresdb
         env:
         - name: POSTGRES_USER
           value: matthias
         - name: POSTGRES_PASSWORD
           value: password
         - name: POSTGRES_DB
           value: mydb
         ports:
         - containerPort: 5432
           name: postgresdb
         volumeMounts:
           - name: data
             mountPath: /var/lib/postgresql/data
